### ISSUE TITLE
PHP 8.1 passing null to function error

### ISSUE THREAD

**Issue by katcher** [rogerbaba/moodle-mod_groupselect#103]
Deprecated:  strtr(): Passing null to parameter #1 ($string) of type string is deprecated in /public/home/mod/groupselect/view.php on line 419

Deprecated:  strtr(): Passing null to parameter #1 ($string) of type string is deprecated in groupselect/view.php on line 420

Deprecated:  strtr(): Passing null to parameter #1 ($string) of type string is deprecated in groupselect/view.php on line 421

Deprecated:  strtr(): Passing null to parameter #1 ($string) of type string is deprecated in groupselect/view.php on line 422

Deprecated:  strtr(): Passing null to parameter #1 ($string) of type string is deprecated in groupselect/view.php on line 418

Deprecated:  strtr(): Passing null to parameter #1 ($string) of type string is deprecated in groupselect/view.php on line 419

Deprecated:  strtr(): Passing null to parameter #1 ($string) of type string is deprecated in groupselect/view.php on line 420

Deprecated:  strtr(): Passing null to parameter #1 ($string) of type string is deprecated in /groupselect/view.php on line 421

Deprecated:  strtr(): Passing null to parameter #1 ($string) of type string is deprecated in groupselect/view.php on line 422

Attempted fix:

$row = array (
                $quote.strtr($r->groupid **?? ''**, $charstoescape).$quote,
                $quote.strtr($r->name **?? ''**, $charstoescape).$quote,
                $quote.strtr($r->description **?? ''**, $charstoescape).$quote,
                $quote.strtr($r->username **?? ''**, $charstoescape).$quote,
                $quote.strtr($r->firstname **?? ''**, $charstoescape).$quote,
                $quote.strtr($r->lastname **?? ''**, $charstoescape).$quote,
                $quote.strtr($r->email **?? ''**, $charstoescape).$quote
        );

**Comment by lucaboesch** [comment]
I put that code in here https://github.com/rogerbaba/moodle-mod_groupselect/pull/104 .
Maybe @rogerbaba will take it in.

Thanks, @katcher !

**Comment by rogerbaba** [comment]
included in next version
