### ISSUE TITLE
Unit tests failing on deprecated text

### ISSUE THREAD

**Issue by azrek** [rogerbaba/moodle-mod_groupselect#64]
Branch: LATEST_STABLE

Unit tests fail on:

) core_string_manager_standard_testcase::test_validate_deprecated_strings_files with data set #121 ('assigngroup_confirm.mod_groupselect')
Failed asserting that 0 matches expected 1.

/var/lib/moodle/lib/tests/string_manager_standard_test.php:114
/var/lib/moodle/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit core_string_manager_standard_testcase lib/tests/string_manager_standard_test.php

This is due to the file:
lang/en/deprecated.txt

Once it's removed, the unit tests pass.

Thanks,
Ghada

**Comment by azrek** [comment]
Hi @rogerbaba  ,

It basically needs a cherry-pick of this commit on master: 2d927e57be9ea47dca4ee51fb75cf8b19e471de6

thanks,
Ghada

**Comment by rogerbaba** [comment]
will be removed in 3.16
