### ISSUE TITLE
Upgrade.php is out of sync with install.xml

### ISSUE THREAD

**Issue by Peterburnett** [rogerbaba/moodle-mod_groupselect#66]
Upgrade.php has a couple of references to schema details that are changed/removed.
1) upgrade.php has no removal script for old removed field 'signuptype'
2) upgrade.php defines field 'intro' with default of 0, install.xml specifies default of null
3) upgrade.php defines field 'supervisionrole' with a variable default, install.xml specifies default of 1

**Comment by rogerbaba** [comment]
fix included in pull request #67
