### ISSUE TITLE
The setting Participants can set and edit group description looks to be applied even when greyed out

### ISSUE THREAD

**Issue by kiratskitizing** [rogerbaba/moodle-mod_groupselect#78]
Replicated using 2020030600 (mod_groupselect)
Moodle 4.0dev (Build: 20200903) and 3.7

Steps to replicate:
1. Create a course.
2. Enrol 2 students.
3. Add a group "groupA". Do not add members.
4. Turn editing on.
5. Add a Group self-selection activity:
General permissions
[ticked] Participants can join groups
[ticked] Participants can leave groups
[ticked] Participants can create groups
[ticked] Participants can set the name of new groups
[ticked] Participants can set and edit group description
6. Untick the setting Participants can create groups.
7. You will notice that the following are greyed-out.
[ticked/greyed] Participants can set the name of new groups
[ticked/greyed] Participants can set and edit group description
8. Save the activity.
9. Log in as the student. Go to the Group self-selection activity.
10. Click "Become member of".
Result: You will see that the student is able to "Edit group description"

11. Log in back as teacher/admin and check the settings again of the Group self-selection.
12. You will see that the following are still greyed out:
[ticked/greyed] Participants can set the name of new groups
[ticked/greyed] Participants can set and edit group description
13. Tick back Participants can create groups and now, the following are enabled again:
[ticked] Participants can set the name of new groups
[ticked] Participants can set and edit group description
14. Untick the Participants can set and edit group description and Save it.

15. Log in back as the student and check if you can still edit group description.
Result: Student is not able to edit description.

Observed: Students can edit the group description even though the setting is greyed out
Should the setting be applied even if it is greyed out and depends on the _Participants can create groups_ when unticked/ticked?

**Comment by rogerbaba** [comment]
Thanks I will check that point.
