### ISSUE TITLE
Please document that the current version works under Moodle 3.10 or 3.11

### ISSUE THREAD

**Issue by jondo** [rogerbaba/moodle-mod_groupselect#81]
... unless there are known problems with these Moodle versions. But it seems there are at least no issues filed yet :)

Currently, https://moodle.org/plugins/mod_groupselect/versions only says that the current plugin version works with Moodle 3.5 to 3.9.

**Comment by rogerbaba** [comment]
will be veriified asap

**Comment by jondo** [comment]
Great! Can you also test with Moodle 4 please?

**Comment by jondo** [comment]
Thank you!
Can you please also test Moodle 4.0? Or should I file a separate issue for that?

**Comment by lucaboesch** [comment]
Sorry if I have to contradict, current master is fine with 4.0 but breaks installation ≤ 3.11 but the pull request #92 would amend it (And also add activity dates. And also GitHub Actions for 3.11.).
