### ISSUE TITLE
Moodle 4 support

### ISSUE THREAD

**Issue by acquaalta** [rogerbaba/moodle-mod_groupselect#83]
Hi,
Could you please add support for Moodle 4?
Even if the current version of the plugin would work on Moodle 4, an official support would be great.

Thanks even for considering it :-)

**Comment by lucaboesch** [comment]
My branch https://github.com/lucaboesch/moodle-mod_groupselect/tree/purpose_monologo has some Moodle 4.0 improvements as the icon and the icon purpose color.

**Comment by acquaalta** [comment]
Thanks a lot , @lucaboesch 
@rogerbaba Is it possible that you'll implement these changes into the official plugin?

Thanks

**Comment by lucaboesch** [comment]
I think you can close this cause since https://github.com/rogerbaba/moodle-mod_groupselect/pull/85 fixed this.
