### ISSUE TITLE
Description displayed twice at top of activity in Moodle 4.0

### ISSUE THREAD

**Issue by haietza** [rogerbaba/moodle-mod_groupselect#87]
The description is duplicated at the top of the activity in Moodle 4.0. I believe they have changed how they render the description and activity completion in 4.0.

**Comment by haietza** [comment]
@rogerbaba Any updates on this issue? We're updating to 4.0 Jan 10 and would love to have it resolved before then. We also noticed in testing that the due date is not displayed on the course page, likely tied to this same issue since description and completion data are tied together in Moodle display.

**Comment by rogerbaba** [comment]
hm I am not able to reproduce this

**Comment by haietza** [comment]
Here is a screenshot of the activity settings with display description enabled and a deadline set.
![Screenshot 2022-11-22 at 4 52 52 PM](https://user-images.githubusercontent.com/669666/203429407-49e55e29-4c5f-4741-8154-8f8c85e61083.png)

Here is a screenshot of the resulting activity view page, showing the description duplicated.
![Screenshot 2022-11-22 at 4 53 07 PM](https://user-images.githubusercontent.com/669666/203429510-0dbb0bf3-4fd1-461f-8f40-dd53915c4c9d.png)

Here is a screenshot of the course page with the deadline missing.
![Screenshot 2022-11-22 at 4 53 22 PM](https://user-images.githubusercontent.com/669666/203429556-09d5ed9d-5a75-4ce9-b367-e6b61a8d81e0.png)

**Comment by rogerbaba** [comment]
Thank the deadline is something new i create a new issue for this, i try to release a Version 4.0 of the plugin for moodle >=4.0 soon.

**Comment by haietza** [comment]
@rogerbaba Has the duplicate description been fixed (and thus the closing of this issue)?

**Comment by rogerbaba** [comment]
@haietza yes will be in the coming release
